// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: google/type/postal_address.proto

package _type

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PostalAddress with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PostalAddress) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PostalAddress with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PostalAddressMultiError, or
// nil if none found.
func (m *PostalAddress) ValidateAll() error {
	return m.validate(true)
}

func (m *PostalAddress) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Revision

	// no validation rules for RegionCode

	// no validation rules for LanguageCode

	// no validation rules for PostalCode

	// no validation rules for SortingCode

	// no validation rules for AdministrativeArea

	// no validation rules for Locality

	// no validation rules for Sublocality

	// no validation rules for Organization

	if len(errors) > 0 {
		return PostalAddressMultiError(errors)
	}

	return nil
}

// PostalAddressMultiError is an error wrapping multiple validation errors
// returned by PostalAddress.ValidateAll() if the designated constraints
// aren't met.
type PostalAddressMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PostalAddressMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PostalAddressMultiError) AllErrors() []error { return m }

// PostalAddressValidationError is the validation error returned by
// PostalAddress.Validate if the designated constraints aren't met.
type PostalAddressValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PostalAddressValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PostalAddressValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PostalAddressValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PostalAddressValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PostalAddressValidationError) ErrorName() string { return "PostalAddressValidationError" }

// Error satisfies the builtin error interface
func (e PostalAddressValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPostalAddress.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PostalAddressValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PostalAddressValidationError{}
