---
name: "Devel (nightly) Release"
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
permissions:
  contents: "write"
  packages: "write"
jobs:
  goreleaser:
    runs-on: "buildjet-4vcpu-ubuntu-2204"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "authzed/actions/setup-go@main"
      - name: "Install snapcraft"
        run: "sudo snap install snapcraft --channel=7.x/stable --classic"
      - uses: "authzed/actions/docker-login@main"
        with:
          quayio_token: "${{ secrets.QUAYIO_PASSWORD }}"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          dockerhub_token: "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}"
      - uses: "docker/setup-qemu-action@v3"
      - uses: "docker/setup-buildx-action@v3"
      - uses: "goreleaser/goreleaser-action@v5"
        with:
          distribution: "goreleaser-pro"
          version: "latest"
          args: "release -f .goreleaser.nightly.yml --clean --nightly"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GORELEASER_KEY: "${{ secrets.GORELEASER_KEY }}"
